### ISSUE TITLE
the specified url reverts to a blank page

### ISSUE THREAD

**Issue by ineuw** [smblott-github/chrome-new-tab-url#3]
Each time https://duckduckgo.com/ is specified and saved for the new tab, it's not sticking. and gets wiped out. At this point a measure of paranoia sets in regarding google related products changing any setting that refers to the above website.

**Comment by smblott-github** [comment]
You're using `Ctrl-Enter` to save, yes?  That is the only way to save the URL.

Are there any error messages on the console?  Use `Ctrl-Shift-I` on the options page to open the console.

**Comment by ineuw** [comment]
Yes, I was using Ctrl-Enter, I just checked the browser in Windows 7 (Comodo Dragon) and it works fine. I will get back again after checking the Chromium installation on Xubuntu.

**Comment by smblott-github** [comment]
I may just change this such that `Enter` on its own works, or perhaps just save on `blur`.

**Comment by ineuw** [comment]
Everything is working fine, in Windows and Xubuntu. Thanks for your quick response to the issue.
