### ISSUE TITLE
Blank URL in new tabs

### ISSUE THREAD

**Issue by df7cb** [smblott-github/chrome-new-tab-url#4]
Hi,

thanks for this extension.

Would it be possible to have the URL bar emptied in new tabs, so I could start typing the URL I want to go to right away without having to hit ^L first?

**Comment by lopezloo** [comment]
Use _about:blank_ as URL. I tried this and adress bar was already selected and ready to write own text.

**Comment by df7cb** [comment]
Wouldn't this defeat the whole idea of the extension?

**Comment by smblott-github** [comment]
Two things:
1. The way Chrome supports setting the new-tab page is to override it in the manifest, so it has to be a constant (so, not something configurable).  So I suspect this isn't possible.
2. This extension was written specifically to get the focus out of the omnibox.  (I use [Vimium](https://chrome.google.com/webstore/detail/vimium/dbepggeogbaibhgnhhndojpepiihcmeb/reviews?hl=en), and for Vimium you want the focus in the page.)

So this is both can't fix and won't fix.  Sorry.
