### ISSUE TITLE
Keep focus on Chrome search bar

### ISSUE THREAD

**Issue by kevinebaugh** [smblott-github/chrome-new-tab-url#5]
Often I `⌘ + T` quickly then start typing my search query. With this (awesome) extension, I have to refocus the search bar every time I open a new tab.

**Comment by smblott-github** [comment]
Thanks, @kevinebaugh.  See [this comment](https://github.com/smblott-github/chrome-new-tab-url/issues/4#issuecomment-212260246) in #4.

Closing, assuming that that answers your question.
