### ISSUE TITLE
Vimium's blank page

### ISSUE THREAD

**Issue by iroedius** [smblott-github/chrome-new-tab-url#7]
If I set `chrome-extension://dbepggeogbaibhgnhhndojpepiihcmeb/pages/blank.html` (Vimium's blank page) as the target URL, I keep getting about:blank when opening a new tab via Ctrl-T. The same URL works fine when set in Vimium's settings and using Vimium's shortcut.

**Comment by smblott-github** [comment]
Hmm.  Thanks, @iroedius.  I'm going to guess that that cannot be fixed.  Chrome is somehow preventing this extension from bouncing you to another extension's (Vimium's) internal page.  Which makes sense from a security perspective.

If you're looking for a blank page (with a very long TTL), you could use [this](http://static.smblott.org/blank.html) or [this](https://smblott.firebaseapp.com/blank).  I cannot guarantee that they'll live forever, but I've no plan to remove them.

**Comment by iroedius** [comment]
Thank you for your suggestion, I will do that for now. Have you considered adding a blank page to this extension? It would always load a little faster than a remote URL.

**Comment by smblott-github** [comment]
Unfortunately, Vimium ~~would~~ **would not** run on such an internal page (Chrome doesn't let other extensions do that).

**Comment by iroedius** [comment]
You mean it **wouldn't** run, right? I see, that's a pity. Thanks for your help and for a nice extension.

**Comment by smblott-github** [comment]
Right.  Oops.
